name: Build and Push Docker Image

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/test.hookcafe:${{ github.sha }} .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/test.hookcafe:${{ github.sha }} ghcr.io/${{ secrets.GHCR_USERNAME }}/test.hookcafe:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/test.hookcafe:${{ github.sha }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/test.hookcafe:latest